Version support and automatic CI build
uxlfoundation/scikit-learn-intelex pull request #2214
Opened 2024-12-07 00:19 UTC by intelkevinputnam

## Description

replaces #1785 

Version of docs built using CI: https://intelkevinputnam.github.io/scikit-learn-intelex/

There are two major changes in this PR:

1. Version switching support
2. CI deployment to GitHub pages via GitHub action

### Version Switching Support

All published versions must be tracked in doc/versions.json as this will allow all subsequent versions of the docs to automatically be able to switch to the latest without needing to rebuild the docs.

The version is supplied by the **installed** version of scikit-learn-intelex (latest by default in the CI script). This way building the docs is not dependent on the oneDAL environment with the goal of making it easier to contribute to and edit the docs. It should also make builds faster.

Since the move to the UXL Foundation, version switching is broken in the latest version of the docs because of there is a hard coded path to the versions.json that no longer exists (it was intel.github.com/scikit-learn-intelex). It also is now settable in the conf.py (html_context)

### CI Deployment to GitHub Pages via GitHub Action

GitHub pages will be updated automatically.  A new directory will be **added** for each version of scikit-learn-intelex. When the same version is built twice, it is overwritten. See ``.github/workflows/publish.yml`` for the script. The branch will need to be changed to ``main`` before it will work on the main branch. I'm not sure it is necessary to have the docs built on every merge into ``main``. Adding ``workflow_dispatch:`` to the list of conditions for running the action can provide a handy "deploy whenever you feel like it" option. 

To build the docs locally, run ``./build-docs.sh``. Docs can be previewed locally by starting a web server (``python3 -m http.server``) in the ``_build`` directory and using ``localhost:8000/scikit-learn-intelex`` as the URL.

---
Checklist to comply with **before moving PR from draft**:

**PR completeness and readability**

- [X] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [X] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [ ] I have added a respective label(s) to PR if I have a permission for that.
- [X] I have resolved any merge conflicts that might occur with the base branch.

2024-12-09 09:37 UTC, david-cortes-intel requested changes

2024-12-09 09:37 UTC, david-cortes-intel commented on doc/build-doc.sh
> +export SPHINXPROJ=scikit-learn-intelex
We also have `daal4py` with docs under `doc/daal4py`.

2024-12-09 09:37 UTC, david-cortes-intel commented on doc/get_doc_version.py
> +def get_version():
@icfaust Could you please look into whether this captures the version number correctly.

2024-12-09 09:37 UTC, david-cortes-intel commented on doc/sources/_static/custom.css
> +div#version-switcher-dropdown {
Question: if we have this line right here, do we still need to add a version selector in the `conf.py` file?
https://github.com/uxlfoundation/scikit-learn-intelex/blob/54aa18b56b853add58d8ea078efae36fb1209741/doc/sources/conf.py#L146

I understand that version selector plugin is meant for ReadTheDocs, so don't know how it plays with these.

2024-12-09 09:37 UTC, david-cortes-intel commented on doc/sources/conf.py
> +version = os.environ.get('DOC_VERSION','')
How about changing the version to "latest" here when it doesn't find the env. variable?

2024-12-09 09:37 UTC, david-cortes-intel commented on doc/versions.json
> +        "name": "2025.0 (latest)",
Could we make this file auto-generated from the releases that we have as github tags instead? It's BTW missing some version numbers, such as 2024.7.0:
https://github.com/uxlfoundation/scikit-learn-intelex/releases

2024-12-09 09:37 UTC, david-cortes-intel commented on .github/workflows/publish.yml
> +        git push -f https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
Question: what happens if something goes wrong during the build? For example, we might run into errors such as failing to import the modules from which autodoc generates documentation, which would manifest as a "warning" being issued but _some_ docs still being built.

Could there be a check for build warnings that would make this script fail (avoiding pushing anything to GH) if something goes wrong?

2024-12-09 09:37 UTC, david-cortes-intel commented on doc/versions.json
> +[
What about "stable" version tag in addition to latest?

2024-12-09 09:43 UTC, david-cortes-intel commented
Perhaps this PR could be a good opportunity to address one topic around the version numbers: in open source projects, version "latest" or "dev" is typically meant for docs from "latest commit of the master branch", while the "last released version" is typically "stable".

This is the case for the docs of the scikit-learn package which this repository builds upon, and for most other machine-learning-related libraries such as gradient boosting frameworks and similar.

Could we make the switch here so that the freshest release would be "stable" and have "latest" as something built periodically from the main branch?

2025-01-10 19:30 UTC, intelkevinputnam commented
> @intelkevinputnam I'm seeing several misrendered things in the docs from your branch.
> 
> For example: ![image](https://private-user-images.githubusercontent.com/180380222/393774005-6a89cef4-6391-4cd5-82ed-235264a44221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MzY4NjcsIm5iZiI6MTczNjUzNjU2NywicGF0aCI6Ii8xODAzODAyMjIvMzkzNzc0MDA1LTZhODljZWY0LTYzOTEtNGNkNS04MmVkLTIzNTI2NGE0NDIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMFQxOTE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTllMzZlYzhkZDI2YmY0NTViMTBlOWYxYjI2OGFkYTY4MjlkMmVmY2NhYTc3MmFjMDA4YTJkOTIzMWU4NjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._CUv7ZEpieMKcP2q6bNfqaGThxujZIjyAN4wCTl9Zyw)
> 
> This is how it looks for me in a local build: ![image](https://private-user-images.githubusercontent.com/180380222/393774162-3509a090-feca-4fc7-be21-2958e787c845.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MzY4NjcsIm5iZiI6MTczNjUzNjU2NywicGF0aCI6Ii8xODAzODAyMjIvMzkzNzc0MTYyLTM1MDlhMDkwLWZlY2EtNGZjNy1iZTIxLTI5NThlNzg3Yzg0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMFQxOTE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTdkZjg2YTkwMmFhYzUxODVhYzc5Y2Q1NGNmOWE0ODA0NDgyMWJhMGY0MGU4ZWY0MDViMmU0NWYwYjA0YTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BG0YexfeNJWwJhLLiv860tS3lpRRhBre7LrpOjQbaXM)

Since the build script is dependent on the latest **released** version of the scikit-learn-intelex package, the changes must not have propagated to it as of the first build. The changes you mention appear to have propagated to the released package now, so the you'll see what you expect if you check again.

2025-01-10 19:33 UTC, intelkevinputnam commented on doc/sources/_static/custom.css
> +div#version-switcher-dropdown {
The version selector isn't related to ReadTheDocs at all. This is a custom version switcher implemented on top of it.

2025-01-10 19:34 UTC, intelkevinputnam commented on doc/sources/conf.py
> +version = os.environ.get('DOC_VERSION','')
If there isn't a version, the build should fail.

2025-01-10 19:40 UTC, intelkevinputnam commented on .github/workflows/publish.yml
> +        git push -f https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
Any errors in the github workflow will stop the docs from publishing. We could turn on "error on warning" in the sphinx build, if we wanted to gate against any issue in the Sphinx build.

2025-01-13 15:11 UTC, david-cortes-intel commented on doc/sources/_static/custom.css
> +div#version-switcher-dropdown {
So can we remove this `"version_selector": True` in our `conf.py` then?

2025-01-13 15:14 UTC, david-cortes-intel commented on doc/versions.json
> +        "name": "2025.0 (latest)",
The list of releases can be obtained programmatically. This repository keeps branches with "rls" in the name for all released versions, which can be obtained with a command like this from the root of the repository:
```
git branch -r | grep rls
```

And since it follows date-based versioning, the most up-to-date one will always be the last one in alphabetical order, as returned by that command. So it should be possible to auto-generate this file with all the releases that exist, and keep it auto-updated to point to the last when a new branch comes in.

2025-01-13 15:15 UTC, david-cortes-intel commented on .github/workflows/publish.yml
> +        git push -f https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
Yes, that'd be ideal, so that we don't accidentally end up with empty docs. But would be better if it could ignore _some_ warnings selectively - currently there are some warnings when building `daal4py` which I'm not sure how to solve and which do not impact the resulting docs that get built.

2025-01-13 15:20 UTC, david-cortes-intel commented on doc/versions.json
> +        "name": "2025.0 (latest)",
Although the issue would be that some versions are missing docs.

2025-01-13 15:27 UTC, david-cortes-intel commented on .github/workflows/publish.yml
> +        git push -f https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
Example benign warnings when building `daal4py`:
```
/home/dcortes/repos/scikit-learn-intelex/doc/daal4py/docstring of daal4py._daal4py.classifier_prediction_result:1: WARNING: duplicate object description of daal4py.classifier_prediction_result, other instance in algorithms, use :noindex: for one of them
```

2025-01-13 15:28 UTC, david-cortes-intel commented on doc/sources/conf.py
> +version = os.environ.get('DOC_VERSION','')
I mean: would be ideal to have a version "latest" building the docs directly from the master branch, for unreleased versions. So in that case, the release versions would have the env. variable whereas the master branch wouldn't.

2025-01-15 13:50 UTC, david-cortes-intel commented on doc/sources/conf.py
> +import json
Looks like this import is not used.

2025-01-15 17:09 UTC, david-cortes-intel commented on doc/sources/_static/custom.css
> +div#version-switcher-dropdown {
Removed the option.

2025-01-15 17:10 UTC, david-cortes-intel commented
Verified that we can indeed push changes to this PR (CC @yuejiaointel )

2025-01-15 20:38 UTC, icfaust commented on .github/workflows/publish.yml
> +        git push -f https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input  let me know if i am missing something, sentence just before this link: "Commits pushed by a GitHub Actions workflow that uses the GITHUB_TOKEN do not trigger a GitHub Pages build."

2025-01-15 21:02 UTC, icfaust commented on doc/get_doc_version.py
> +def get_version():
i would prefer if we got rid of this file entirely and replaced it with
```
DOC_VERSION=$(python -m pip freeze | grep -oP "(?<=scikit-learn-intelex==)\d*\.\d*")
```

2025-01-15 21:09 UTC, icfaust commented on doc/versions.json
> +        "name": "2025.0 (latest)",
I have to agree with @david-cortes-intel on this one, we could technically have the ```(latest)``` tag be updated on a github ```create``` trigger when it has ```rls``` in it.

2025-01-15 21:40 UTC, icfaust reviewed
Here is my initial review, we probably need someone to review the js, since I have no idea on that.

2025-01-15 21:40 UTC, icfaust commented on .github/workflows/publish.yml
> +        sudo apt install -y pandoc git
```suggestion
        sudo apt install -y pandoc

```
How come git is necessary?

2025-01-15 21:40 UTC, icfaust commented on .github/workflows/publish.yml
> +        echo Generating version $DOC_VERSION
```suggestion
        DOC_VERSION=$(python -m pip freeze | grep -oP "(?<=scikit-learn-intelex==)\d*\.\d*")
        echo Generating version $DOC_VERSION
        echo "DOC_VERSION=${DOC_VERSION}" >> "$GITHUB_ENV"
```
Add it to the github environment to save some work/lines going forward.

2025-01-15 21:40 UTC, icfaust commented on .github/workflows/publish.yml
> +        cd ..
```suggestion
```
With the previous suggestion these 3 lines are unnecessary as ```DOC_VERSION``` will be propagated in the environment between steps.

2025-01-15 21:40 UTC, icfaust commented on .github/workflows/publish.yml
> +        mv _build/scikit-learn-intelex ../../output
```suggestion
        doc/build-doc.sh
        mv doc/_build/scikit-learn-intelex ../output
```
Sorry since I am not so knowledgeable on the docs side. If build-doc.sh doesn't have the right permissions, we can set those in the repo to what is necessary (does it hurt to store build-doc.sh as 755 instead)?

2025-01-15 21:40 UTC, icfaust commented on .github/workflows/publish.yml
> +        rm -rf doc
Does this ```rm``` wipe the ```git checkout``` of the build-doc.sh?

2025-01-21 07:53 UTC, david-cortes-intel commented on .github/workflows/publish.yml
> +        pip3 install scikit-learn-intelex
I had forgotten to comment here but: we'd probably want to change this logic towards either building from source, or downloading artifacts from github - otherwise this wouldn't work out when pushing to release branches (would build docs for the wrong version), nor when trying to build docs for unreleased versions.

2025-01-24 15:32 UTC, icfaust commented on .github/workflows/publish.yml
> +        pip3 install scikit-learn-intelex
I totally agree.

2025-02-26 12:40 UTC, closed without merging